services:
  api:
    image: python:3.8
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    volumes:
      - ./api:/app
      - ."./wait-for-it.sh:/app/wait-for-it.sh"

    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      API_OCUPACION: http://api-containers:5000/occupancy
      API_POWER: http://api-containers:5000/power
      API_TEMPERATURA: http://api-containers:5000/temperature
      API_SEGURIDAD: http://api-containers:5000/security
    
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - sensores
      - consumer

    restart: always

networks:
  sensores:
    driver: bridge
    external: true
  consumer:
    driver: bridge
    external: true