services:
  api:
    image: python:3.8
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    volumes:
      - ./api:/app

    environment:
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq

      

    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:5000/health"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - sensores
      - consumer

networks:
  sensores:
    driver: bridge
    external: true
  consumer:
    driver: bridge
    external: true