services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

    networks:
      - consumer
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always


  consumer_occupancy:
    image: pandira/practica1-consumers:v1.0.4
    volumes:
      - ./consumer:/app
      - ./data:/data
      - ./wait-for-it.sh:/app/wait-for-it.sh

    working_dir: /app
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "occupancy_consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    networks:
      - consumer


  consumer_power:
    image: pandira/practica1-consumers:v1.0.4

    volumes:
      - ./consumer:/app
      - ./datnetworkNamea:/data
      - ./wait-for-it.sh:/app/wait-for-it.sh

    working_dir: /app
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "power_consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    networks:
      - consumer


  consumer_security:
    image: pandira/practica1-consumers:v1.0.4
    volumes:
      - ./consumer:/app
      - ./data:/data
      - ./wait-for-it.sh:/app/wait-for-it.sh

    working_dir: /app
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "security_consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    networks:
      - consumer


  consumer_temperature:
    image: pandira/practica1-consumers:v1.0.4

    volumes:
      - ./consumer:/app
      - ./data:/data
      - ./wait-for-it.sh:/app/wait-for-it.sh

    working_dir: /app
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "temperature_consumer.py"]
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=password
    depends_on:
      - rabbitmq
    networks:
      - consumer


  api-containers:
    image: pandira/practica1-consumers:v1.0.4

    volumes:
      - ./api:/app
      - ./data:/data  # CSVs
      - ./wait-for-it.sh:/app/wait-for-it.sh

    working_dir: /app
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "python", "-u", "api.py"]
    environment:
      - PATH_FILE_OCUPACION=/data/occupancy.csv
      - PATH_FILE_POWER=/data/power.csv
      - PATH_FILE_SECURITY=/data/security.csv
      - PATH_FILE_TEMPERATURE=/data/temperature.csv

    depends_on:
      - rabbitmq
    networks:
      - consumer
    ports:
      - "5001:5000"


networks:
  consumer:
    driver: bridge
    external: true